name: cicdworkflow1

on:
  push:
    branches:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: v1.0
        #token: ${{ secrets.GIT_PAT }}
        token: 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
        


    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        #output: 'trivy-results.txt'
        severity: 'CRITICAL'




    # - name: Send Slack Notification (if vulnerabilities found)
    #   uses: 8398a7/actions-slack@v3
    #   with:
    #    text: 'Vulnerabilities found in the codebase.'
    #    channel: 'your-slack-channel'
    #   env:
    #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


    # - name: Build Docker Image
    #   run: |
    #      docker build -t your-image-name:${{ github.sha }} .


    # - name: Push Docker Image to Docker Hub
    #   run: |
    #        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    #        docker push your-image-name:${{ github.sha }}
    
    
    # - name: Sign Docker Image
    #   run: |
    #          cosign sign -key your-signing-key.pem your-image-name:${{ github.sha }}


    # - name: Send Slack Notification (on success)
    #   uses: 8398a7/actions-slack@v3
    #   with:
    #     text: |
    #        Name: Ganesh Kumar
    #        Matriculation number: A0285944M
    #        Email: e1221756@u.nus.edu
    #        Repository: ${{ github.repository }}
    #        Docker Hub URL: Your Docker Hub URL
    #     channel: 'your-slack-channel'
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


    




