name: cicdworkflow1

on:
  push:
    branches:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref}}
        token:  ${{github.token}}
        

        

    - name: scan for vulnerablity with trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        exit-code: '1'
        output: 'trivy-results.txt'
        severity: 'CRITICAL'

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        # SLACK_CHANNEL: general
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'success maesss'
        SLACK_TITLE: NNN TITLE
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}



    
  # build_and_push:
  #     needs: cve_scan
  #     runs-on: windows-latest
  #     steps:
  #       - name: Check Out Code
  #         uses: actions/checkout@v2
  
  #       - name: Build and Push Docker Image
  #         id: build
  #         uses: docker/build-push-action@v2
  #         with:
  #           context: . # Adjust the Dockerfile context
  #           tags: "your-image-name:${{ github.sha }}"
  #           push: true
  #           registry: docker.io
  #         env:
  #           DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #           DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}



    # - name: Send Slack Notification (on success)
    #   uses: 8398a7/actions-slack@v3
    #   with:
    #     text: |
    #        Name: Ganesh Kumar
    #        Matriculation number: A0285944M
    #        Email: e1221756@u.nus.edu
    #        Repository: ${{ github.repository }}
    #        Docker Hub URL: Your Docker Hub URL
    #     channel: 'your-slack-channel'
    #   env:
    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


    




