name: scanning

on:
  push:
    branches:
      - 'v*.*'

jobs:
  security_scan:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.ps1 | powershell -command -
      continue-on-error: true

    - name: Security Scanning
      run: |
        trivy --exit-code 0 your-image-to-scan:tag > scan-report.txt
      continue-on-error: true

    - name: Generate Tabular Report
      run: |
        type scan-report.txt | findstr /v /c:"0 vulnerabilities" > scan-report-table.txt
      continue-on-error: true

    - name: Send Slack Notification (if vulnerabilities found)
      run: |
        find /c /v "" scan-report-table.txt
        IF %ERRORLEVEL% NEQ 0 (
          # Add your Slack notification command here
        )
      continue-on-error: true
